<template>
  <q-page class="q-pa-md micro-page">
    <div class="row items-center q-mb-md q-col-gutter-md">
      <div class="col">
        <div class="text-h5 text-weight-bold">{{ heading }}</div>
        <div class="text-caption text-grey-6">{{ companyStore.companyName || 'Empresa' }} · módulo isolado por empresa</div>
      </div>
      <div class="col-auto" v-if="mode === 'clientes'"><q-btn color="primary" icon="person_add" label="Novo cliente" no-caps @click="openClient()" /></div>
      <div class="col-auto" v-if="mode === 'creditos'"><q-btn color="primary" icon="add" label="Novo crédito" no-caps @click="openCredit()" /></div>
      <div class="col-auto" v-if="mode === 'financiamentos'"><q-btn color="primary" icon="add" label="Novo financiamento" no-caps @click="openFunding()" /></div>
    </div>

    <q-tabs v-model="activeTab" dense align="left" no-caps active-color="primary" indicator-color="primary" class="bg-white q-mb-md rounded-borders shadow-1">
      <q-route-tab v-for="item in nav" :key="item.to" :to="item.to" :name="item.key" :icon="item.icon" :label="item.label" />
    </q-tabs>

    <div v-if="loading" class="text-center q-pa-xl"><q-spinner-dots size="42px" color="primary" /></div>
    <template v-else>
      <section v-if="mode === 'dashboard'">
        <div class="row q-col-gutter-md q-mb-md">
          <div v-for="kpi in kpis" :key="kpi.label" class="col-12 col-sm-6 col-lg-3"><q-card flat bordered><q-card-section><div class="text-caption text-grey-6">{{ kpi.label }}</div><div class="text-h5 text-weight-bold q-mt-xs">{{ kpi.money ? money(kpi.value) : kpi.value }}</div></q-card-section></q-card></div>
        </div>
        <div class="row q-col-gutter-md">
          <div class="col-12 col-lg-6"><q-card flat bordered><q-card-section class="text-subtitle1 text-weight-bold">Carteira por sector</q-card-section><q-card-section><div v-for="(amount, name) in dashboard.sectors" :key="name" class="q-mb-sm"><div class="row justify-between text-caption"><span>{{ name }}</span><b>{{ money(amount) }}</b></div><q-linear-progress rounded size="9px" :value="maxSector ? amount / maxSector : 0" color="teal" class="q-mt-xs" /></div></q-card-section></q-card></div>
          <div class="col-12 col-lg-6"><q-card flat bordered><q-card-section class="text-subtitle1 text-weight-bold">Classes de risco (MZN)</q-card-section><q-card-section><div v-for="risk in risks" :key="risk" class="row items-center q-py-sm"><q-badge :color="riskColors[risk]" class="q-mr-sm">Classe {{ risk }}</q-badge><div class="col"><q-linear-progress rounded size="10px" :value="maxRisk ? dashboard.riskClasses[risk] / maxRisk : 0" :color="riskColors[risk]" /></div><div class="text-right text-caption q-ml-md" style="width:110px">{{ money(dashboard.riskClasses[risk]) }}</div></div></q-card-section></q-card></div>
          <div class="col-12"><q-card flat bordered><q-card-section class="text-subtitle1 text-weight-bold">Créditos em atraso</q-card-section><q-table :rows="dashboard.overdue || []" :columns="overdueColumns" row-key="id" flat dense :rows-per-page-options="[10,25]" no-data-label="Sem créditos em atraso"><template v-slot:body-cell-total_em_divida="p"><q-td :props="p" class="text-right">{{ money(p.row.total_em_divida) }}</q-td></template><template v-slot:body-cell-classe_risco="p"><q-td :props="p"><q-badge :color="riskColors[p.row.classe_risco]">{{ p.row.classe_risco || '—' }}</q-badge></q-td></template></q-table></q-card></div>
        </div>
      </section>

      <q-card v-else-if="mode === 'clientes'" flat bordered>
        <q-table :rows="clients" :columns="clientColumns" row-key="id" :filter="search" :rows-per-page-options="[10,25,50]" flat><template v-slot:top-right><q-input v-model="search" dense outlined debounce="250" placeholder="Pesquisar clientes"><template v-slot:append><q-icon name="search" /></template></q-input></template><template v-slot:body-cell-actions="p"><q-td :props="p"><q-btn flat round dense icon="edit" color="primary" @click="openClient(p.row)"/><q-btn flat round dense icon="delete" color="negative" @click="removeClient(p.row)"/></q-td></template></q-table>
      </q-card>

      <q-card v-else-if="mode === 'creditos'" flat bordered>
        <q-table :rows="credits" :columns="creditColumns" row-key="id" :filter="search" :rows-per-page-options="[10,25,50]" flat><template v-slot:top-right><q-input v-model="search" dense outlined debounce="250" placeholder="Pesquisar crédito"><template v-slot:append><q-icon name="search" /></template></q-input></template><template v-slot:body-cell-montante_capital="p"><q-td :props="p" class="text-right">{{ money(p.row.montante_capital) }}</q-td></template><template v-slot:body-cell-total_em_divida="p"><q-td :props="p" class="text-right">{{ money(p.row.total_em_divida) }}</q-td></template><template v-slot:body-cell-actions="p"><q-td :props="p"><q-btn flat round dense icon="payments" color="primary" @click="paymentFor(p.row)"/></q-td></template></q-table>
      </q-card>

      <q-card v-else-if="mode === 'pagamentos'" flat bordered>
        <q-card-section class="row items-center q-col-gutter-sm"><div class="col-12 col-sm-5"><q-select v-model="payment.credito_id" :options="creditOptions" emit-value map-options outlined dense label="Crédito" /></div><div class="col-12 col-sm-3"><q-input v-model.number="payment.montante" outlined dense type="number" min="0.01" label="Valor pago (MZN)" /></div><div class="col-12 col-sm-2"><q-select v-model="payment.forma" :options="paymentMethods" outlined dense label="Forma" /></div><div class="col-12 col-sm-2"><q-input v-model="payment.data_pagamento" type="date" outlined dense label="Data" /></div><div class="col-12 text-right"><q-btn color="primary" icon="save" label="Registar pagamento" no-caps :loading="saving" :disable="!payment.credito_id || !(Number(payment.montante)>0)" @click="savePayment" /></div></q-card-section>
        <q-separator/><q-table :rows="payments" :columns="paymentColumns" row-key="id" flat :rows-per-page-options="[10,25,50]"><template v-slot:body-cell-capital_pago="p"><q-td :props="p" class="text-right">{{ money(p.row.capital_pago) }}</q-td></template><template v-slot:body-cell-juro_pago="p"><q-td :props="p" class="text-right">{{ money(p.row.juro_pago) }}</q-td></template></q-table>
      </q-card>

      <div v-else-if="mode === 'financiamentos'" class="column q-gutter-md">
        <q-card flat bordered><q-card-section class="row items-center"><div class="text-subtitle1 text-weight-bold">Fontes de financiamento</div><q-space/><q-btn flat color="primary" icon="add" label="Movimento de activos" no-caps @click="openMovement()"/></q-card-section><q-table :rows="funding" :columns="fundingColumns" row-key="id" flat :rows-per-page-options="[10,25,50]"><template v-slot:body-cell-montante="p"><q-td :props="p" class="text-right">{{ money(p.row.montante) }}</q-td></template><template v-slot:body-cell-actions="p"><q-td :props="p"><q-btn flat round dense icon="edit" color="primary" @click="openFunding(p.row)"/><q-btn flat round dense icon="delete" color="negative" @click="removeFunding(p.row)"/></q-td></template></q-table></q-card>
        <q-card flat bordered><q-card-section class="text-subtitle1 text-weight-bold">Configuração e capital</q-card-section><q-card-section class="row q-col-gutter-sm items-center"><div class="col-6 col-md-2"><q-input v-model.number="config.taxa_juro_min" type="number" outlined dense label="Taxa mínima (%)"/></div><div class="col-6 col-md-2"><q-input v-model.number="config.taxa_juro_max" type="number" outlined dense label="Taxa máxima (%)"/></div><div class="col-6 col-md-2"><q-input v-model.number="config.prazo_min" type="number" outlined dense label="Prazo min. (meses)"/></div><div class="col-6 col-md-2"><q-input v-model.number="config.prazo_max" type="number" outlined dense label="Prazo max. (meses)"/></div><div class="col-6 col-md-2"><q-input v-model.number="config.capital_inicial" type="number" outlined dense label="Capital inicial"/></div><div class="col-6 col-md-2"><q-input v-model.number="config.capital_actual" type="number" outlined dense label="Capital actual"/></div><div class="col-12 text-right"><q-btn color="primary" label="Guardar configuração" no-caps :loading="saving" @click="saveConfig"/></div></q-card-section></q-card>
        <q-card flat bordered><q-card-section class="text-subtitle1 text-weight-bold">Movimentos financeiros mensais</q-card-section><q-table :rows="movements" :columns="movementColumns" row-key="id" flat :rows-per-page-options="[10,25]"><template v-slot:body-cell-montante="p"><q-td :props="p" class="text-right">{{ money(p.row.montante) }}</q-td></template><template v-slot:body-cell-actions="p"><q-td :props="p"><q-btn flat round dense icon="edit" color="primary" @click="openMovement(p.row)"/></q-td></template></q-table></q-card>
      </div>

      <section v-else-if="mode === 'reportes'">
        <q-card flat bordered class="q-mb-md"><q-card-section><div class="text-h6 text-weight-bold">Empresa {{ companyStore.companyName || 'Empresa' }} <span class="text-caption text-grey-6">({{ report?.tenant?.workers ?? '—' }} trabalhadores)</span></div><div class="text-caption text-grey-6">{{ report?.tenant?.address || '' }} · {{ report?.tenant?.province || '' }} · {{ report?.tenant?.phone || '' }}</div><div class="row q-col-gutter-sm items-end q-mt-sm"><div class="col-6 col-md-3"><q-input v-model="period.start" type="date" outlined dense label="Data início"/></div><div class="col-6 col-md-3"><q-input v-model="period.end" type="date" outlined dense label="Data fim"/></div><div class="col-auto"><q-btn color="primary" icon="preview" label="Pré-visualizar" no-caps :loading="saving" @click="previewReport"/></div><div class="col-auto"><q-btn color="positive" icon="download" label="Gerar Excel BM" no-caps :loading="downloading" @click="downloadExcel"/></div><div class="col-auto"><q-btn outline color="negative" icon="picture_as_pdf" label="Exportar PDF" no-caps :disable="!report" @click="downloadPdf"/></div></div></q-card-section></q-card>
        <div v-if="report" class="column q-gutter-md">
          <q-card flat bordered><q-card-section class="text-subtitle1 text-weight-bold">2.1 Carteira de crédito — MZN</q-card-section><q-markup-table dense flat separator="cell"><thead><tr><th>Indicador</th><th class="text-right">Capital</th><th class="text-right">Juro</th><th class="text-right">Total</th></tr></thead><tbody><tr v-for="row in volumeRows" :key="row.label"><td>{{ row.label }}</td><td class="text-right">{{ money(row.capital) }}</td><td class="text-right">{{ money(row.interest) }}</td><td class="text-right">{{ money(row.capital+row.interest) }}</td></tr></tbody></q-markup-table><div class="row q-pa-md q-gutter-md"><span>Créditos concedidos: <b>{{ report.loanCounts.granted }}</b></span><span>Reembolsados: <b>{{ report.loanCounts.repaid }}</b></span><span>Clientes activos: <b>{{ report.clients.total }}</b></span></div></q-card>
          <div class="row q-col-gutter-md"><div class="col-12 col-md-6"><q-card flat bordered><q-card-section class="text-subtitle1 text-weight-bold">Concedidos por sector</q-card-section><q-markup-table dense flat><tbody><tr v-for="(amount,sector) in report.sectors" :key="sector"><td>{{ sector }}</td><td class="text-right">{{ money(amount) }}</td></tr></tbody></q-markup-table></q-card></div><div class="col-12 col-md-6"><q-card flat bordered><q-card-section class="text-subtitle1 text-weight-bold">Carteira em risco</q-card-section><q-markup-table dense flat><thead><tr><th>Classe</th><th class="text-right">Capital</th><th class="text-right">Juro</th><th class="text-right">Total</th></tr></thead><tbody><tr v-for="risk in risks" :key="risk"><td>Classe {{ risk }}</td><td class="text-right">{{ money(report.riskClasses[risk].capital) }}</td><td class="text-right">{{ money(report.riskClasses[risk].interest) }}</td><td class="text-right">{{ money(report.riskClasses[risk].capital+report.riskClasses[risk].interest) }}</td></tr></tbody></q-markup-table></q-card></div></div>
          <q-card flat bordered><q-card-section class="text-subtitle1 text-weight-bold">2.2–3. Situação financeira</q-card-section><q-card-section class="row q-col-gutter-md"><div class="col-6 col-md-3">Taxa mensal: {{ report.rates.min }}%–{{ report.rates.max }}%</div><div class="col-6 col-md-3">Prazo: {{ report.rates.termMin }}–{{ report.rates.termMax }} meses</div><div class="col-6 col-md-3">Capital inicial: {{ money(report.capital.initial) }}</div><div class="col-6 col-md-3">Capital actual: {{ money(report.capital.current) }}</div></q-card-section><q-markup-table dense flat separator="cell"><thead><tr><th>Activo</th><th v-for="(month,i) in report.period.months" :key="month">Mês {{ i+1 }} · {{ month }}</th></tr></thead><tbody><tr><td>Caixa</td><td v-for="(v,i) in report.assets.cash" :key="i" class="text-right">{{ money(v) }}</td></tr><tr><td>Bancos</td><td v-for="(v,i) in report.assets.banks" :key="i" class="text-right">{{ money(v) }}</td></tr><tr><td>Outros Activos</td><td v-for="(v,i) in report.assets.other" :key="i" class="text-right">{{ money(v) }}</td></tr></tbody></q-markup-table></q-card>
        </div>
      </section>
    </template>

    <q-dialog v-model="dialog" persistent><q-card style="width:560px;max-width:95vw"><q-card-section class="row items-center"><div class="text-h6">{{ dialogTitle }}</div><q-space/><q-btn flat round icon="close" v-close-popup/></q-card-section><q-card-section class="row q-col-gutter-sm">
      <template v-if="dialogType==='client'"><div class="col-12"><q-input v-model="form.nome" outlined dense label="Nome completo *"/></div><div class="col-6"><q-select v-model="form.sexo" :options="['Homem','Mulher','Outro']" outlined dense label="Sexo"/></div><div class="col-6"><q-select v-model="form.sector_actividade" :options="sectors" outlined dense label="Sector"/></div><div class="col-6"><q-input v-model="form.numero_doc" outlined dense label="Nº documento"/></div><div class="col-6"><q-input v-model="form.telefone" outlined dense label="Telefone"/></div><div class="col-12"><q-input v-model="form.email" outlined dense label="Email"/></div><div class="col-12"><q-input v-model="form.endereco" outlined dense label="Endereço"/></div></template>
      <template v-else-if="dialogType==='credit'"><div class="col-12"><q-select v-model="form.cliente_id" :options="clientOptions" emit-value map-options outlined dense label="Cliente *"/></div><div class="col-6"><q-input v-model.number="form.montante_capital" type="number" min="1" outlined dense label="Capital (MZN) *"/></div><div class="col-6"><q-input v-model.number="form.taxa_juro_mensal" type="number" min="0" step="0.01" outlined dense label="Juro mensal (%) *"/></div><div class="col-6"><q-input v-model.number="form.prazo_meses" type="number" min="1" outlined dense label="Prazo (meses) *"/></div><div class="col-6"><q-input v-model="form.data_concessao" type="date" outlined dense label="Data de concessão *"/></div><div class="col-12"><q-select v-model="form.sector_finalidade" :options="sectors" outlined dense label="Sector/finalidade"/></div><div v-if="installmentEstimate" class="col-12 text-caption">Prestação estimada: {{ money(installmentEstimate) }} · Juros totais: {{ money(totalInterestEstimate) }}</div></template>
      <template v-else-if="dialogType==='funding'"><div class="col-12"><q-input v-model="form.descricao" outlined dense label="Descrição *"/></div><div class="col-6"><q-select v-model="form.tipo" :options="fundingTypes" emit-value map-options outlined dense label="Origem de capital"/></div><div class="col-6"><q-input v-model.number="form.montante" type="number" outlined dense label="Montante (MZN) *"/></div><div class="col-6"><q-input v-model="form.data_entrada" type="date" outlined dense label="Data de entrada *"/></div><div class="col-6"><q-input v-model="form.origem" outlined dense label="Origem / entidade"/></div><div class="col-12"><q-select v-model="form.categoria_periodo" :options="fundingCategories" emit-value map-options clearable outlined dense label="Categoria do período (2.4)"/></div></template>
      <template v-else><div class="col-6"><q-select v-model="form.tipo" :options="assetTypes" emit-value map-options outlined dense label="Activo"/></div><div class="col-6"><q-input v-model.number="form.mes" type="number" min="1" max="3" outlined dense label="Mês do período (1–3)"/></div><div class="col-6"><q-input v-model="form.data" type="date" outlined dense label="Data"/></div><div class="col-6"><q-input v-model.number="form.montante" type="number" outlined dense label="Montante"/></div></template>
    </q-card-section><q-card-actions align="right" class="q-pa-md"><q-btn flat label="Cancelar" v-close-popup/><q-btn color="primary" label="Guardar" :loading="saving" @click="saveDialog"/></q-card-actions></q-card></q-dialog>
  </q-page>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { useQuasar } from 'quasar'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { api } from '@/boot/axios'
import { useCompanyStore } from '@/stores/company'

const route = useRoute(), $q = useQuasar(), companyStore = useCompanyStore()
const nav = [{key:'dashboard',to:'/admin/microcredito/dashboard',icon:'space_dashboard',label:'Painel'},{key:'clientes',to:'/admin/microcredito/clientes',icon:'groups',label:'Clientes'},{key:'creditos',to:'/admin/microcredito/creditos',icon:'request_quote',label:'Créditos'},{key:'pagamentos',to:'/admin/microcredito/pagamentos',icon:'payments',label:'Pagamentos'},{key:'financiamentos',to:'/admin/microcredito/financiamentos',icon:'savings',label:'Financiamentos'},{key:'reportes',to:'/admin/microcredito/reportes',icon:'description',label:'Reportes BM'}]
const mode = computed(() => route.path.split('/').pop()), activeTab = computed(() => mode.value)
const titles = {dashboard:'Microcrédito · Painel',clientes:'Clientes de microcrédito',creditos:'Créditos e amortização',pagamentos:'Registo de pagamentos',financiamentos:'Fontes e situação financeira',reportes:'Reporte trimestral · Banco de Moçambique'}
const heading = computed(() => titles[mode.value] || 'Microcrédito')
const loading = ref(false), saving = ref(false), downloading = ref(false), search = ref(''), dialog = ref(false), dialogType = ref(''), dialogId = ref(null), report = ref(null)
const dashboard = ref({ portfolio:0,riskAmount:0,riskPercent:0,activeClients:0,activeCredits:0,sectors:{},riskClasses:{I:0,II:0,III:0,IV:0},overdue:[] })
const clients=ref([]),credits=ref([]),payments=ref([]),funding=ref([]),movements=ref([]), config=ref({taxa_juro_min:0,taxa_juro_max:0,prazo_min:1,prazo_max:6,capital_inicial:0,capital_actual:0})
const sectors=['Comércio','Agricultura','Pecuária','Indústria','Serviços','Consumo','Outros'], risks=['I','II','III','IV'],riskColors={I:'green',II:'amber-8',III:'orange-9',IV:'negative'},paymentMethods=['M-Pesa','BCI','eMola','Dinheiro'],fundingTypes=[{label:'Capitais próprios',value:'Proprio'},{label:'Alheios nacionais',value:'Alheio_Nacional'},{label:'Alheios estrangeiros',value:'Alheio_Estrangeiro'}],fundingCategories=[{label:'Empréstimo obtido',value:'Emprestimo'},{label:'Donativo',value:'Donativo'},{label:'Aumento de capital próprio',value:'Aumento_Capital'}],assetTypes=[{label:'Caixa',value:'Caixa'},{label:'Bancos',value:'Bancos'},{label:'Outros activos',value:'Outros_Activos'}]
const today=new Date().toISOString().slice(0,10), period=reactive({start:'2025-10-01',end:'2025-12-31'}),payment=reactive({credito_id:null,montante:null,forma:'Dinheiro',data_pagamento:today}),form=reactive({})
const money = n => `${new Intl.NumberFormat('pt-MZ',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)} MZN`
const maxSector=computed(()=>Math.max(0,...Object.values(dashboard.value.sectors||{}))),maxRisk=computed(()=>Math.max(0,...Object.values(dashboard.value.riskClasses||{})))
const kpis=computed(()=>[{label:'Carteira activa',value:dashboard.value.portfolio,money:true},{label:'Em risco',value:`${money(dashboard.value.riskAmount)} · ${dashboard.value.riskPercent}%`,money:false},{label:'Clientes activos',value:dashboard.value.activeClients},{label:'Créditos em curso',value:dashboard.value.activeCredits}])
const installmentEstimate=computed(()=>{const p=Number(form.montante_capital)||0,r=(Number(form.taxa_juro_mensal)||0)/100,n=Number(form.prazo_meses)||0;return p>0&&n>0?(r?p*r/(1-Math.pow(1+r,-n)):p/n):0}),totalInterestEstimate=computed(()=>Math.max(0,installmentEstimate.value*(Number(form.prazo_meses)||0)-(Number(form.montante_capital)||0)))
const clientOptions=computed(()=>clients.value.filter(c=>c.estado==='Activo').map(c=>({label:`${c.nome} · ${c.sexo} · ${c.sector_actividade}`,value:c.id}))),creditOptions=computed(()=>credits.value.filter(c=>Number(c.total_em_divida)>0&&c.estado!=='Abatido').map(c=>({label:`${c.codigo} · ${c.cliente_nome} · ${money(c.total_em_divida)}`,value:c.id})))
const overdueColumns=[{name:'codigo',label:'Código',field:'codigo',align:'left'},{name:'cliente_nome',label:'Cliente',field:'cliente_nome',align:'left'},{name:'dias_atraso',label:'Dias atraso',field:'dias_atraso',align:'right'},{name:'classe_risco',label:'Classe',field:'classe_risco',align:'center'},{name:'total_em_divida',label:'Em dívida',field:'total_em_divida',align:'right'}]
const clientColumns=[{name:'nome',label:'Nome',field:'nome',align:'left',sortable:true},{name:'sexo',label:'Sexo',field:'sexo',align:'left'},{name:'sector_actividade',label:'Sector',field:'sector_actividade',align:'left'},{name:'telefone',label:'Telefone',field:'telefone',align:'left'},{name:'estado',label:'Estado',field:'estado',align:'left'},{name:'actions',label:'Acções',field:'id',align:'right'}]
const creditColumns=[{name:'codigo',label:'Código',field:'codigo',align:'left'},{name:'cliente_nome',label:'Cliente',field:'cliente_nome',align:'left'},{name:'montante_capital',label:'Capital',field:'montante_capital',align:'right'},{name:'taxa_juro_mensal',label:'Taxa/mês',field:r=>`${r.taxa_juro_mensal}%`,align:'right'},{name:'prazo_meses',label:'Meses',field:'prazo_meses',align:'right'},{name:'data_concessao',label:'Concessão',field:'data_concessao',align:'center'},{name:'estado',label:'Estado',field:'estado',align:'left'},{name:'total_em_divida',label:'Em dívida',field:'total_em_divida',align:'right'},{name:'actions',label:'Pagamento',field:'id',align:'center'}]
const paymentColumns=[{name:'data_pagamento',label:'Data',field:'data_pagamento',align:'left'},{name:'codigo',label:'Crédito',field:'codigo',align:'left'},{name:'cliente_nome',label:'Cliente',field:'cliente_nome',align:'left'},{name:'numero_prestacao',label:'Prestação',field:'numero_prestacao',align:'center'},{name:'capital_pago',label:'Capital pago',field:'capital_pago',align:'right'},{name:'juro_pago',label:'Juro pago',field:'juro_pago',align:'right'},{name:'forma',label:'Forma',field:'forma',align:'left'}]
const fundingColumns=[{name:'descricao',label:'Descrição',field:'descricao',align:'left'},{name:'tipo',label:'Tipo',field:r=>fundingTypes.find(o=>o.value===r.tipo)?.label||r.tipo,align:'left'},{name:'data_entrada',label:'Data',field:'data_entrada',align:'center'},{name:'origem',label:'Origem',field:'origem',align:'left'},{name:'montante',label:'Montante',field:'montante',align:'right'},{name:'actions',label:'Acções',field:'id',align:'right'}]
const movementColumns=[{name:'tipo',label:'Activo',field:r=>assetTypes.find(o=>o.value===r.tipo)?.label||r.tipo,align:'left'},{name:'mes',label:'Mês do trimestre',field:r=>`Mês ${r.mes}`,align:'center'},{name:'data',label:'Data',field:'data',align:'center'},{name:'montante',label:'Montante',field:'montante',align:'right'},{name:'actions',label:'Acções',field:'id',align:'right'}]
const volumeRows=computed(()=>report.value?[{label:'Concedidos no período',...report.value.volume.granted},{label:'Reembolsados no período',...report.value.volume.repaid},{label:'Abatidos no período',...report.value.volume.writtenOff},{label:'Carteira activa/vigente',...report.value.volume.active},{label:'Carteira em risco',...report.value.volume.risk}]:[])
const dialogTitle=computed(()=>({client:dialogId.value?'Editar cliente':'Novo cliente',credit:'Conceder crédito',funding:dialogId.value?'Editar financiamento':'Novo financiamento',movement:dialogId.value?'Editar movimento':'Novo movimento'}[dialogType.value]||'Registo'))
async function load(){loading.value=true;try{if(mode.value==='dashboard'){dashboard.value=(await api.get('/api/microcredito/dashboard')).data.result}else if(mode.value==='clientes'){clients.value=(await api.get('/api/microcredito/clientes')).data.result}else if(mode.value==='creditos'){credits.value=(await api.get('/api/microcredito/creditos')).data.result}else if(mode.value==='pagamentos'){[credits.value,payments.value]=await Promise.all([api.get('/api/microcredito/creditos').then(r=>r.data.result),api.get('/api/microcredito/pagamentos').then(r=>r.data.result)])}else if(mode.value==='financiamentos'){[funding.value,movements.value,config.value]=await Promise.all([api.get('/api/microcredito/financiamentos').then(r=>r.data.result),api.get('/api/microcredito/movimentos').then(r=>r.data.result),api.get('/api/microcredito/configuracao').then(r=>r.data.result)])}else if(mode.value==='reportes'){/* metadata comes from preview; company details are never client-supplied */}}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'Falha ao carregar módulo de microcrédito'})}finally{loading.value=false}}
watch(()=>route.path,load);onMounted(load)
function resetForm(values={}){Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,values)}
function openClient(row){dialogId.value=row?.id||null;dialogType.value='client';resetForm(row||{sexo:'Outro',sector_actividade:'Outros',estado:'Activo'});dialog.value=true}
async function openCredit(){if(!clients.value.length)clients.value=(await api.get('/api/microcredito/clientes')).data.result;dialogId.value=null;dialogType.value='credit';resetForm({data_concessao:today,taxa_juro_mensal:Number(config.value.taxa_juro_min)||5,prazo_meses:Number(config.value.prazo_min)||6,sector_finalidade:'Outros'});dialog.value=true}
function openFunding(row){dialogId.value=row?.id||null;dialogType.value='funding';resetForm(row||{tipo:'Proprio',data_entrada:today,categoria_periodo:'Aumento_Capital'});dialog.value=true}
function openMovement(row){dialogId.value=row?.id||null;dialogType.value='movement';resetForm(row||{tipo:'Caixa',mes:1,data:today,montante:0});dialog.value=true}
function paymentFor(row){payment.credito_id=row.id;payment.montante=null;payment.data_pagamento=today;}
async function saveDialog(){saving.value=true;try{const id=dialogId.value;const url=dialogType.value==='client'?'/api/microcredito/clientes':dialogType.value==='credit'?'/api/microcredito/creditos':dialogType.value==='funding'?'/api/microcredito/financiamentos':'/api/microcredito/movimentos';if(dialogType.value==='credit'){const r=await api.post(url,form);$q.notify({type:'positive',message:`Crédito ${r.data.result.codigo} criado com ${r.data.result.prestacoes.length} prestações`})}else if(id)await api.put(`${url}/${id}`,form);else await api.post(url,form);dialog.value=false;await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'Não foi possível guardar'})}finally{saving.value=false}}
async function removeClient(row){$q.dialog({title:'Remover cliente',message:`Remover ${row.nome}?`,cancel:true,persistent:true}).onOk(async()=>{try{await api.delete(`/api/microcredito/clientes/${row.id}`);await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'Não foi possível remover'})}})}
async function removeFunding(row){$q.dialog({title:'Remover financiamento',message:`Remover ${row.descricao}?`,cancel:true,persistent:true}).onOk(async()=>{try{await api.delete(`/api/microcredito/financiamentos/${row.id}`);await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'Não foi possível remover'})}})}
async function savePayment(){saving.value=true;try{await api.post(`/api/microcredito/creditos/${payment.credito_id}/pagamentos`,payment);payment.montante=null;$q.notify({type:'positive',message:'Pagamento registado e risco recalculado'});await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'Não foi possível registar pagamento'})}finally{saving.value=false}}
async function saveConfig(){saving.value=true;try{config.value=(await api.put('/api/microcredito/configuracao',config.value)).data.result;$q.notify({type:'positive',message:'Configuração guardada'})}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'Configuração inválida'})}finally{saving.value=false}}
async function previewReport(){saving.value=true;try{report.value=(await api.get('/api/microcredito/reportes/preview',{params:{dataInicio:period.start,dataFim:period.end}})).data.result}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'Não foi possível gerar a pré-visualização'})}finally{saving.value=false}}
async function downloadExcel(){downloading.value=true;try{const r=await api.post('/api/microcredito/reportes/gerar',{dataInicio:period.start,dataFim:period.end},{responseType:'blob'});const href=URL.createObjectURL(new Blob([r.data],{type:r.headers['content-type']}));const a=document.createElement('a');a.href=href;a.download=`BM_Reporte_${(companyStore.companyName||'empresa').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-')}_${period.end.slice(0,4)}-T${Math.floor((Number(period.end.slice(5,7))-1)/3)+1}.xlsx`;a.click();URL.revokeObjectURL(href);$q.notify({type:'positive',message:'Excel do modelo BM gerado'})}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'Falha ao gerar Excel'})}finally{downloading.value=false}}
function downloadPdf(){if(!report.value)return;const doc=new jsPDF({orientation:'landscape'});doc.setFontSize(15);doc.text(`Reporte trimestral BM · ${report.value.tenant.name}`,14,15);doc.setFontSize(10);doc.text(`${report.value.period.start} — ${report.value.period.end} · Operador: ${report.value.operator}`,14,22);autoTable(doc,{startY:28,head:[['Indicador','Capital','Juro','Total']],body:volumeRows.value.map(x=>[x.label,money(x.capital),money(x.interest),money(x.capital+x.interest)])});autoTable(doc,{startY:doc.lastAutoTable.finalY+6,head:[['Sector','Montante concedido']],body:Object.entries(report.value.sectors).map(([s,n])=>[s,money(n)])});doc.save(`BM_Reporte_${report.value.tenant.name.replace(/[^a-z0-9]+/gi,'-')}_${report.value.period.end}.pdf`)}
</script>

<style scoped>
.micro-page{max-width:1600px;margin:auto}.q-card{border-radius:12px}.rounded-borders{border-radius:12px}
</style>
